version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/bitbucket.org/danstutzman/wellsaid-backend
    steps:
      - checkout
      - run: go test -v ./...
